application: fortune-ru
version: 0
runtime: python
api_version: 1

handlers:

- url: /(.*\.(ico|jpg|gif|bmp|png|css|js|txt))
  static_files: static/\1
  upload: static/(.*\.(ico|jpg|gif|bmp|png|css|js|txt))


- url: /static
  static_dir: static

- url: /admin
  script: main.py
  login: required
  secure: always

#- url: /remote_api
#  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
#  login: admin

- url: .*
  script: main.py
  
